import { Technique } from "./technique.ts"

export const TECHNIQUE_SCORES: Record<Technique, number> = {
  FULL_HOUSE: 4,
  NAKED_SINGLE: 4,
  HIDDEN_SINGLE: 14,
  LOCKED_PAIR: 40,
  LOCKED_TRIPLE: 60,
  LOCKED_CANDIDATES: 50,
  NAKED_PAIR: 60,
  NAKED_TRIPLE: 80,
  NAKED_QUADRUPLE: 120,
  HIDDEN_PAIR: 70,
  HIDDEN_TRIPLE: 100,
  HIDDEN_QUADRUPLE: 150,
  SKYSCRAPER: 200,
  X_WING: 180,
  SWORDFISH: 250,
  TWO_STRING_KITE: 190,
}
