import { Schema } from "effect"
import { DifficultyLevel } from "./difficulty.ts"

// =============================================================================
// Solving Techniques (matching Hodoku)
// =============================================================================

export const Technique = Schema.Literal(
  // Singles
  "FULL_HOUSE",
  "NAKED_SINGLE",
  "HIDDEN_SINGLE",
  
  // Intersections
  "LOCKED_PAIR",
  "LOCKED_TRIPLE",
  "LOCKED_CANDIDATES",
  
  // Subsets
  "NAKED_PAIR",
  "NAKED_TRIPLE",
  "NAKED_QUADRUPLE",
  "HIDDEN_PAIR",
  "HIDDEN_TRIPLE",
  "HIDDEN_QUADRUPLE",
  
  // Basic Fish
  "X_WING",
  "SWORDFISH",
  "JELLYFISH",
  "SQUIRMBAG",
  "WHALE",
  "LEVIATHAN",
  
  // Finned Fish
  "FINNED_X_WING",
  "FINNED_SWORDFISH",
  "FINNED_JELLYFISH",
  "FINNED_SQUIRMBAG",
  "FINNED_WHALE",
  "FINNED_LEVIATHAN",
  "SASHIMI_X_WING",
  "SASHIMI_SWORDFISH",
  "SASHIMI_JELLYFISH",
  "SASHIMI_SQUIRMBAG",
  "SASHIMI_WHALE",
  "SASHIMI_LEVIATHAN",
  
  // Franken/Mutant Fish
  "FRANKEN_X_WING",
  "FRANKEN_SWORDFISH",
  "FRANKEN_JELLYFISH",
  "FRANKEN_SQUIRMBAG",
  "FRANKEN_WHALE",
  "FRANKEN_LEVIATHAN",
  "MUTANT_X_WING",
  "MUTANT_SWORDFISH",
  "MUTANT_JELLYFISH",
  "MUTANT_SQUIRMBAG",
  "MUTANT_WHALE",
  "MUTANT_LEVIATHAN",
  "FINNED_FRANKEN_X_WING",
  "FINNED_FRANKEN_SWORDFISH",
  "FINNED_FRANKEN_JELLYFISH",
  "FINNED_FRANKEN_SQUIRMBAG",
  "FINNED_FRANKEN_WHALE",
  "FINNED_FRANKEN_LEVIATHAN",
  "FINNED_MUTANT_X_WING",
  "FINNED_MUTANT_SWORDFISH",
  "FINNED_MUTANT_JELLYFISH",
  "FINNED_MUTANT_SQUIRMBAG",
  "FINNED_MUTANT_WHALE",
  "FINNED_MUTANT_LEVIATHAN",
  
  // Single Digit Patterns
  "SKYSCRAPER",
  "TWO_STRING_KITE",
  "EMPTY_RECTANGLE",
  
  // Wings
  "XY_WING",
  "XYZ_WING",
  "W_WING",
  
  // Chains
  "X_CHAIN",
  "XY_CHAIN",
  "REMOTE_PAIR",
  "NICE_LOOP",
  "CONTINUOUS_NICE_LOOP",
  "DISCONTINUOUS_NICE_LOOP",
  "AIC",
  
  // Colors
  "SIMPLE_COLORS",
  "MULTI_COLORS",
  
  // Uniqueness
  "UNIQUENESS_1",
  "UNIQUENESS_2",
  "UNIQUENESS_3",
  "UNIQUENESS_4",
  "UNIQUENESS_5",
  "UNIQUENESS_6",
  "BUG_PLUS_1",
  "HIDDEN_RECTANGLE",
  
  // ALS
  "ALS_XZ",
  "ALS_XY_WING",
  "ALS_XY_CHAIN",
  "DEATH_BLOSSOM",
  
  // Advanced
  "SUE_DE_COQ",
  "TEMPLATE_SET",
  "TEMPLATE_DEL",
  
  // Last Resort
  "FORCING_CHAIN",
  "FORCING_NET",
  "BRUTE_FORCE"
)
export type Technique = typeof Technique.Type

// Technique scores (from Hodoku)
export const TECHNIQUE_SCORES: Record<Technique, number> = {
  // Singles
  FULL_HOUSE: 4,
  NAKED_SINGLE: 4,
  HIDDEN_SINGLE: 14,
  
  // Intersections
  LOCKED_PAIR: 40,
  LOCKED_TRIPLE: 60,
  LOCKED_CANDIDATES: 50,
  
  // Subsets
  NAKED_PAIR: 60,
  NAKED_TRIPLE: 80,
  NAKED_QUADRUPLE: 120,
  HIDDEN_PAIR: 70,
  HIDDEN_TRIPLE: 100,
  HIDDEN_QUADRUPLE: 150,
  
  // Basic Fish
  X_WING: 140,
  SWORDFISH: 150,
  JELLYFISH: 160,
  SQUIRMBAG: 470,
  WHALE: 470,
  LEVIATHAN: 470,
  
  // Finned Fish
  FINNED_X_WING: 150,
  FINNED_SWORDFISH: 160,
  FINNED_JELLYFISH: 170,
  FINNED_SQUIRMBAG: 480,
  FINNED_WHALE: 480,
  FINNED_LEVIATHAN: 480,
  SASHIMI_X_WING: 150,
  SASHIMI_SWORDFISH: 160,
  SASHIMI_JELLYFISH: 170,
  SASHIMI_SQUIRMBAG: 480,
  SASHIMI_WHALE: 480,
  SASHIMI_LEVIATHAN: 480,
  
  // Franken/Mutant
  FRANKEN_X_WING: 180,
  FRANKEN_SWORDFISH: 190,
  FRANKEN_JELLYFISH: 200,
  FRANKEN_SQUIRMBAG: 490,
  FRANKEN_WHALE: 490,
  FRANKEN_LEVIATHAN: 490,
  MUTANT_X_WING: 220,
  MUTANT_SWORDFISH: 230,
  MUTANT_JELLYFISH: 240,
  MUTANT_SQUIRMBAG: 530,
  MUTANT_WHALE: 530,
  MUTANT_LEVIATHAN: 530,
  FINNED_FRANKEN_X_WING: 190,
  FINNED_FRANKEN_SWORDFISH: 200,
  FINNED_FRANKEN_JELLYFISH: 210,
  FINNED_FRANKEN_SQUIRMBAG: 500,
  FINNED_FRANKEN_WHALE: 500,
  FINNED_FRANKEN_LEVIATHAN: 500,
  FINNED_MUTANT_X_WING: 230,
  FINNED_MUTANT_SWORDFISH: 240,
  FINNED_MUTANT_JELLYFISH: 250,
  FINNED_MUTANT_SQUIRMBAG: 540,
  FINNED_MUTANT_WHALE: 540,
  FINNED_MUTANT_LEVIATHAN: 540,
  
  // Patterns
  SKYSCRAPER: 130,
  TWO_STRING_KITE: 150,
  EMPTY_RECTANGLE: 120,
  
  // Wings
  XY_WING: 160,
  XYZ_WING: 180,
  W_WING: 150,
  
  // Chains
  X_CHAIN: 200,
  XY_CHAIN: 260,
  REMOTE_PAIR: 110,
  NICE_LOOP: 280,
  CONTINUOUS_NICE_LOOP: 280,
  DISCONTINUOUS_NICE_LOOP: 280,
  AIC: 280,
  
  // Colors
  SIMPLE_COLORS: 110,
  MULTI_COLORS: 120,
  
  // Uniqueness
  UNIQUENESS_1: 100,
  UNIQUENESS_2: 100,
  UNIQUENESS_3: 100,
  UNIQUENESS_4: 100,
  UNIQUENESS_5: 100,
  UNIQUENESS_6: 100,
  BUG_PLUS_1: 100,
  HIDDEN_RECTANGLE: 100,
  
  // ALS
  ALS_XZ: 300,
  ALS_XY_WING: 320,
  ALS_XY_CHAIN: 340,
  DEATH_BLOSSOM: 350,
  
  // Advanced
  SUE_DE_COQ: 330,
  TEMPLATE_SET: 400,
  TEMPLATE_DEL: 450,
  
  // Last Resort
  FORCING_CHAIN: 500,
  FORCING_NET: 700,
  BRUTE_FORCE: 10000,
}

// Difficulty assignment per technique (from Hodoku)
export const TECHNIQUE_DIFFICULTY: Record<Technique, DifficultyLevel> = {
  // Easy
  FULL_HOUSE: "EASY",
  NAKED_SINGLE: "EASY",
  HIDDEN_SINGLE: "EASY",
  
  // Medium
  LOCKED_PAIR: "MEDIUM",
  LOCKED_TRIPLE: "MEDIUM",
  LOCKED_CANDIDATES: "MEDIUM",
  NAKED_PAIR: "MEDIUM",
  NAKED_TRIPLE: "MEDIUM",
  HIDDEN_PAIR: "MEDIUM",
  HIDDEN_TRIPLE: "MEDIUM",
  
  // Hard
  NAKED_QUADRUPLE: "HARD",
  HIDDEN_QUADRUPLE: "HARD",
  X_WING: "HARD",
  SWORDFISH: "HARD",
  JELLYFISH: "HARD",
  XY_WING: "HARD",
  XYZ_WING: "HARD",
  W_WING: "HARD",
  SKYSCRAPER: "HARD",
  TWO_STRING_KITE: "HARD",
  EMPTY_RECTANGLE: "HARD",
  REMOTE_PAIR: "HARD",
  BUG_PLUS_1: "HARD",
  UNIQUENESS_1: "HARD",
  UNIQUENESS_2: "HARD",
  UNIQUENESS_3: "HARD",
  UNIQUENESS_4: "HARD",
  UNIQUENESS_5: "HARD",
  UNIQUENESS_6: "HARD",
  HIDDEN_RECTANGLE: "HARD",
  SIMPLE_COLORS: "HARD",
  MULTI_COLORS: "HARD",
  FINNED_X_WING: "HARD",
  SASHIMI_X_WING: "HARD",
  
  // Unfair
  SQUIRMBAG: "UNFAIR",
  WHALE: "UNFAIR",
  LEVIATHAN: "UNFAIR",
  FINNED_SWORDFISH: "UNFAIR",
  FINNED_JELLYFISH: "UNFAIR",
  FINNED_SQUIRMBAG: "UNFAIR",
  FINNED_WHALE: "UNFAIR",
  FINNED_LEVIATHAN: "UNFAIR",
  SASHIMI_SWORDFISH: "UNFAIR",
  SASHIMI_JELLYFISH: "UNFAIR",
  SASHIMI_SQUIRMBAG: "UNFAIR",
  SASHIMI_WHALE: "UNFAIR",
  SASHIMI_LEVIATHAN: "UNFAIR",
  FRANKEN_X_WING: "UNFAIR",
  FRANKEN_SWORDFISH: "UNFAIR",
  FRANKEN_JELLYFISH: "UNFAIR",
  FRANKEN_SQUIRMBAG: "UNFAIR",
  FRANKEN_WHALE: "UNFAIR",
  FRANKEN_LEVIATHAN: "UNFAIR",
  X_CHAIN: "UNFAIR",
  XY_CHAIN: "UNFAIR",
  NICE_LOOP: "UNFAIR",
  CONTINUOUS_NICE_LOOP: "UNFAIR",
  DISCONTINUOUS_NICE_LOOP: "UNFAIR",
  AIC: "UNFAIR",
  ALS_XZ: "UNFAIR",
  ALS_XY_WING: "UNFAIR",
  ALS_XY_CHAIN: "UNFAIR",
  DEATH_BLOSSOM: "UNFAIR",
  SUE_DE_COQ: "UNFAIR",
  FINNED_FRANKEN_X_WING: "UNFAIR",
  FINNED_FRANKEN_SWORDFISH: "UNFAIR",
  FINNED_FRANKEN_JELLYFISH: "UNFAIR",
  FINNED_FRANKEN_SQUIRMBAG: "EXTREME",
  FINNED_FRANKEN_WHALE: "EXTREME",
  FINNED_FRANKEN_LEVIATHAN: "EXTREME",
  
  // Extreme
  MUTANT_X_WING: "EXTREME",
  MUTANT_SWORDFISH: "EXTREME",
  MUTANT_JELLYFISH: "EXTREME",
  MUTANT_SQUIRMBAG: "EXTREME",
  MUTANT_WHALE: "EXTREME",
  MUTANT_LEVIATHAN: "EXTREME",
  FINNED_MUTANT_X_WING: "EXTREME",
  FINNED_MUTANT_SWORDFISH: "EXTREME",
  FINNED_MUTANT_JELLYFISH: "EXTREME",
  FINNED_MUTANT_SQUIRMBAG: "EXTREME",
  FINNED_MUTANT_WHALE: "EXTREME",
  FINNED_MUTANT_LEVIATHAN: "EXTREME",
  TEMPLATE_SET: "EXTREME",
  TEMPLATE_DEL: "EXTREME",
  FORCING_CHAIN: "EXTREME",
  FORCING_NET: "EXTREME",
  BRUTE_FORCE: "EXTREME",
}
